steps:
  - name: gcr.io/cloud-builders/gsutil
    args: [ 'cp','gs://config_${PROJECT_ID}/ecosystem-frontend-config.yml','src/main/resources/application.yml' ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: [ '-c','cat src/main/resources/application.yml' ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    # replaces the first occurrence of the 'default'
    args: [ '-c','sed -i s/default/${_APP_ENGINE_TARGET_SERVICE}/ src/main/appengine/app.yaml' ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - sed -E -i 's|(min_instances:).[0-9]|\1 ${_APP_ENGINE_MIN_INSTANCES}|' src/main/appengine/app.yaml
  - name: 'maven:3-jdk-11'
    entrypoint: 'mvn'
    args: [ 'package','appengine:deploy' ]
substitutions:
  _APP_ENGINE_TARGET_SERVICE: default # default App Engine service
  _APP_ENGINE_MIN_INSTANCES: '0'
