var Configuration = {
    LOGIN_ID: '${LOGIN_ID}',
    DOMICILE: '${DOMICILE}',
    CURRENCY: '${CURRENCY}',
    VAT: 'STANDARD',
    LOGO: "",
    ACCOUNT_STEWARD_STORAGE: '${ACCOUNT_STEWARD_STORAGE}',
    PRODUCT_BILLING_STORAGE: '${PRODUCT_BILLING_STORAGE}',
    ACCOUNT_STEWARD_API_ROOT: '${ACCOUNT_STEWARD_API_ROOT}',
    PRODUCT_BILLING_API_ROOT: '${PRODUCT_BILLING_API_ROOT}',
    SEARCH_API_ROOT: '${SEARCH_API_ROOT}',
    MAPS_API_KEY: '${MAPS_API_KEY}'
};
