gwt:
  account-steward-storage: "https://account.turnon.cloud/storage/steward/v1"
  product-billing-storage: "https://billing.turnon.cloud/storage/billing/v1"
  billing-processor-storage: "https://bill.turnon.cloud/storage/bill/v1"

  account-steward-api-root: "https://account.turnon.cloud/api/steward/v1"
  product-billing-api-root: "https://billing.turnon.cloud/api/billing/v1"
  billing-processor-api-root: "https://bill.turnon.cloud/api/bill/v1"
  payment-processor-api-root: "https://payment.turnon.cloud/api/payment/v1"
  search-api-root: "https://search.turnon.cloud/api/search/v1"