runtime: java11
service: default

handlers:
  - url: (/billing\.widget/billing\.widget\.nocache\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 0s
  - url: (/robots\.txt)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 1d
  - url: (/billing\.widget/.*\..*)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/contact\.widget/contact\.widget\.nocache\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 0s
  - url: (/contact\.widget/.*\..*)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/my\.account\.widget/my\.account\.widget\.nocache\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 0s
  - url: (/my\.account\.widget/.*\..*\.css)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/my\.account\.widget/.*\..*\.png)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/my\.account\.widget/.*\..*\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/my\.account\.widget/.*\..*)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/product\.widget/product\.widget\.nocache\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 0s
  - url: (/product\.widget/.*\..*)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/purchase\.widget/purchase\.widget\.nocache\.js)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 0s
  - url: (/purchase\.widget/.*\..*)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/favicon\.ico)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/apple-touch-icon\.png)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: (/apple-touch-icon-precomposed\.png)
    static_files: __static__\1
    upload: __NOT_USED__
    require_matching_file: True
    login: optional
    secure: always
    expiration: 365d
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
automatic_scaling:
  min_instances: 0
