package biz.turnonline.ecosystem.origin.frontend.steward;

import java.io.Serializable;
import java.util.Date;

/**
 * If security code is missing in the subscription request, a verification link (incl. security code) will be sent to the contact email to validate newsletter subscription. Until validated the email will be added as a new contact however unsubscribed from the newsletter. Generated security code will be kept and associated with contact email.  If modification date is being provided the subscription request will be accepted only if this modification date is after the time kept by the service (last wins). Useful if requests are processed asynchronously. If not provided, the subscription requests will be processed in order as they comes.
 **/
public class NewsletterSubscription
        implements Serializable
{
    private static final long serialVersionUID = 348478938149177893L;

    private Boolean subscribe = false;

    private String code;

    private Date modificationDate;

    /**
     * The boolean indication whether the contact will be subscribed or unsubscribed from the newsletter.
     **/
    public NewsletterSubscription subscribe( Boolean subscribe )
    {
        this.subscribe = subscribe;
        return this;
    }

    public Boolean getSubscribe()
    {
        return subscribe;
    }

    public void setSubscribe( Boolean subscribe )
    {
        this.subscribe = subscribe;
    }

    /**
     * The security code originally generated by the service.
     **/
    public NewsletterSubscription code( String code )
    {
        this.code = code;
        return this;
    }

    public String getCode()
    {
        return code;
    }

    public void setCode( String code )
    {
        this.code = code;
    }

    /**
     * The newsletter subscription modification date and time. A client specified time when the request has been originated.
     **/
    public NewsletterSubscription modificationDate( Date modificationDate )
    {
        this.modificationDate = modificationDate;
        return this;
    }

    public Date getModificationDate()
    {
        return modificationDate;
    }

    public void setModificationDate( Date modificationDate )
    {
        this.modificationDate = modificationDate;
    }
}

